apiVersion: apps/v1
kind: Deployment
metadata:
  name: lwm-alpha
  labels:
    app: lwm-alpha

spec:
  replicas: 3

  selector:
    matchLabels:
      app: lwm-alpha

  template:
    metadata:
      labels:
        app: lwm-alpha

    spec:
      # ✅ REQUIRED for pulling image from AWS ECR
      imagePullSecrets:
        - name: ecr-secret

      containers:
        - name: cont1
          image: 445567098528.dkr.ecr.ap-south-1.amazonaws.com/alpha:16-e0d09e1
          imagePullPolicy: Always

          ports:
            - containerPort: 8000   # ✅ FastAPI default port

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          env:
            - name: ENV
              value: "dev"
