apiVersion: v1
kind: Service
metadata:
  name: lwm-alpha-svc
  labels:
    app: lwm-alpha
spec:
  type: LoadBalancer
  selector:
    app: lwm-alpha
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
